spring:
  datasource:
    username: root
    password: '123456789a'
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/media?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 10MB
  mail:
    host: smtp.qq.com
    username: 837447352@qq.com
    password: tbtshyehhponbbfa
    default-encoding: UTF-8
tengxun:
  accessKey: AKIDELHhzAodcP1Yu76yFNOF6qOkuseOwlOv
  secretKey: SimXFtQmyzufHjFiicKrYAg1Pm0iLtGR
  bucket: ap-shanghai
  bucketName: picture-1253231183
  path: https://picture-1253231183.cos.ap-shanghai.myqcloud.com
mail:
  activateUrl: http://localhost:8080/api/user/activateEmail?